//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchThree.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchThree.API.Resources.Localization.ru-RU", typeof(Localization_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достигнут максимальный уровень.
        /// </summary>
        internal static string CommonMaxLevelReachedTextKey {
            get {
                return ResourceManager.GetString("CommonMaxLevelReachedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ну пинганул.
        /// </summary>
        internal static string CommonPingOk {
            get {
                return ResourceManager.GetString("CommonPingOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определено.
        /// </summary>
        internal static string CommonUndefinedTextKey {
            get {
                return ResourceManager.GetString("CommonUndefinedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось авторизоваться. Пожалуйста, попробуйте еще раз позже. {0}.
        /// </summary>
        internal static string ExceptionAuthorizationTextKey {
            get {
                return ResourceManager.GetString("ExceptionAuthorizationTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы были забанены на {0} часов.
        /// </summary>
        internal static string ExceptionBannedTextKey {
            get {
                return ResourceManager.GetString("ExceptionBannedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квест уже выполнен сегодня.
        /// </summary>
        internal static string ExceptionDailyLoginCompletedTodayTextKey {
            get {
                return ResourceManager.GetString("ExceptionDailyLoginCompletedTodayTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла непредвиденная ошибка.
        /// </summary>
        internal static string ExceptionDefaultTextKey {
            get {
                return ResourceManager.GetString("ExceptionDefaultTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный элемент не существует.
        /// </summary>
        internal static string ExceptionNoDataFoundTextKey {
            get {
                return ResourceManager.GetString("ExceptionNoDataFoundTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно средств на балансе.
        /// </summary>
        internal static string ExceptionNotEnoughBalanceTextKey {
            get {
                return ResourceManager.GetString("ExceptionNotEnoughBalanceTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно энергии.
        /// </summary>
        internal static string ExceptionNotEnoughEnergyTextKey {
            get {
                return ResourceManager.GetString("ExceptionNotEnoughEnergyTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Квест уже завершен.
        /// </summary>
        internal static string ExceptionQuestAlreadyCompletedTextKey {
            get {
                return ResourceManager.GetString("ExceptionQuestAlreadyCompletedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Задание больше недоступно.
        /// </summary>
        internal static string ExceptionQuestOutdatedTextKey {
            get {
                return ResourceManager.GetString("ExceptionQuestOutdatedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не все условия были выполнены.
        /// </summary>
        internal static string ExceptionQuestsConditionNotMetTextKey {
            get {
                return ResourceManager.GetString("ExceptionQuestsConditionNotMetTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия улучшения не были выполнены.
        /// </summary>
        internal static string ExceptionUpgradeConditionsTextKey {
            get {
                return ResourceManager.GetString("ExceptionUpgradeConditionsTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось обработать запрос. Пожалуйста, обновите страницу и попробуйте снова.
        /// </summary>
        internal static string ExceptionValidationTextKey {
            get {
                return ResourceManager.GetString("ExceptionValidationTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига краба.
        /// </summary>
        internal static string LeagueCrabFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueCrabFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краб.
        /// </summary>
        internal static string LeagueCrabTextKey {
            get {
                return ResourceManager.GetString("LeagueCrabTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига дельфина.
        /// </summary>
        internal static string LeagueDolphinFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueDolphinFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дельфин.
        /// </summary>
        internal static string LeagueDolphinTextKey {
            get {
                return ResourceManager.GetString("LeagueDolphinTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига рыбы.
        /// </summary>
        internal static string LeagueFishFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueFishFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рыба.
        /// </summary>
        internal static string LeagueFishTextKey {
            get {
                return ResourceManager.GetString("LeagueFishTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига горбатого кита.
        /// </summary>
        internal static string LeagueHumpbackFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueHumpbackFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горбатый кит.
        /// </summary>
        internal static string LeagueHumpbackTextKey {
            get {
                return ResourceManager.GetString("LeagueHumpbackTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига осьминога.
        /// </summary>
        internal static string LeagueOctopusFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueOctopusFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осьминог.
        /// </summary>
        internal static string LeagueOctopusTextKey {
            get {
                return ResourceManager.GetString("LeagueOctopusTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига акулы.
        /// </summary>
        internal static string LeagueSharkFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueSharkFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акула.
        /// </summary>
        internal static string LeagueSharkTextKey {
            get {
                return ResourceManager.GetString("LeagueSharkTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига креветки.
        /// </summary>
        internal static string LeagueShrimpFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueShrimpFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Креветка.
        /// </summary>
        internal static string LeagueShrimpTextKey {
            get {
                return ResourceManager.GetString("LeagueShrimpTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лига кита.
        /// </summary>
        internal static string LeagueWhaleFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueWhaleFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кит.
        /// </summary>
        internal static string LeagueWhaleTextKey {
            get {
                return ResourceManager.GetString("LeagueWhaleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://t.me/PingWinGame_chat_ru.
        /// </summary>
        internal static string LinkGroupChatTextKey {
            get {
                return ResourceManager.GetString("LinkGroupChatTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://t.me/PingWinGame_ru.
        /// </summary>
        internal static string LinkPingwinNewsChannelTextKey {
            get {
                return ResourceManager.GetString("LinkPingwinNewsChannelTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Присоединяйтесь к клубу любителей кастомных эмодзи.
        /// </summary>
        internal static string QuestBePremiumUserDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestBePremiumUserDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Премиум клуб.
        /// </summary>
        internal static string QuestBePremiumUserTittleTextKey {
            get {
                return ResourceManager.GetString("QuestBePremiumUserTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получи дополнительную награду за первого приглашенного друга.
        /// </summary>
        internal static string QuestInvite1FriendDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestInvite1FriendDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пригласи 1 друга.
        /// </summary>
        internal static string QuestInvite1FriendTittleTextKey {
            get {
                return ResourceManager.GetString("QuestInvite1FriendTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получите дополнительную награду за первых двух приглашенных друзей.
        /// </summary>
        internal static string QuestInvite3FriendDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestInvite3FriendDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пригласи 3 друга.
        /// </summary>
        internal static string QuestInvite3FriendTittleTextKey {
            get {
                return ResourceManager.GetString("QuestInvite3FriendTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получите дополнительную награду за первых пяти приглашенных друзей.
        /// </summary>
        internal static string QuestInvite5FriendDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestInvite5FriendDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пригласи 5 друзей.
        /// </summary>
        internal static string QuestInvite5FriendTittleTextKey {
            get {
                return ResourceManager.GetString("QuestInvite5FriendTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купи энергетик за звезды.
        /// </summary>
        internal static string QuestPurchase1EnergyDrinkTittleTextKey {
            get {
                return ResourceManager.GetString("QuestPurchase1EnergyDrinkTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купи 3 энергетика за звезды.
        /// </summary>
        internal static string QuestPurchase3EnergyDrinkTittleTextKey {
            get {
                return ResourceManager.GetString("QuestPurchase3EnergyDrinkTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купи 5 энергетиков за звезды.
        /// </summary>
        internal static string QuestPurchase5EnergyDrinkTittleTextKey {
            get {
                return ResourceManager.GetString("QuestPurchase5EnergyDrinkTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстанавливай энергию, чтобы быстрее прокачиваться.
        /// </summary>
        internal static string QuestPurchaseEnergyDrinkDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestPurchaseEnergyDrinkDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поддержка, общение, FAQ - все там.
        /// </summary>
        internal static string QuestSubscribeToGroupChatDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestSubscribeToGroupChatDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вступай в наш ТГ чат.
        /// </summary>
        internal static string QuestSubscribeToGroupChatTittleTextKey {
            get {
                return ResourceManager.GetString("QuestSubscribeToGroupChatTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Узнавайте новости одним из первых.
        /// </summary>
        internal static string QuestSubscribeToNewsChannelDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestSubscribeToNewsChannelDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подпишись на наш ТГ канал.
        /// </summary>
        internal static string QuestSubscribeToNewsChannelTittleTextKey {
            get {
                return ResourceManager.GetString("QuestSubscribeToNewsChannelTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стартовый бонус для внимательных. Секретный код спрятан где-то в TG канале.
        /// </summary>
        internal static string QuestWelcomeMysteryCodeDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestWelcomeMysteryCodeDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Охота за секретным кодом.
        /// </summary>
        internal static string QuestWelcomeMysteryCodeTittleTextKey {
            get {
                return ResourceManager.GetString("QuestWelcomeMysteryCodeTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергия.
        /// </summary>
        internal static string UpgradeCategoryEnergyTextKey {
            get {
                return ResourceManager.GetString("UpgradeCategoryEnergyTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Крипта.
        /// </summary>
        internal static string UpgradeCategoryFieldElementsTextKey {
            get {
                return ResourceManager.GetString("UpgradeCategoryFieldElementsTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игровое поле.
        /// </summary>
        internal static string UpgradeCategoryFieldTextKey {
            get {
                return ResourceManager.GetString("UpgradeCategoryFieldTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дневной лимит исчерпан.
        /// </summary>
        internal static string UpgradeEnergyDrinkBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyDrinkBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстанавливает {0} энергии.
        /// </summary>
        internal static string UpgradeEnergyDrinkDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyDrinkDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергетик.
        /// </summary>
        internal static string UpgradeEnergyDrinkHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyDrinkHeaderTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достигните {0} уровня запаса энергии.
        /// </summary>
        internal static string UpgradeEnergyRecoveryBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyRecoveryBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повышает скорость восстановления энергии c {0} сек до {1} сек.
        /// </summary>
        internal static string UpgradeEnergyRecoveryDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyRecoveryDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость восстановления.
        /// </summary>
        internal static string UpgradeEnergyRecoveryHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyRecoveryHeaderTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пригласите еще {0} друга.
        /// </summary>
        internal static string UpgradeEnergyReserveBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyReserveBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличивает запас энергии на 5.
        /// </summary>
        internal static string UpgradeEnergyReserveDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyReserveDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запас энергии.
        /// </summary>
        internal static string UpgradeEnergyReserveHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyReserveHeaderTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличивает размер поля на 1 клетку.
        /// </summary>
        internal static string UpgradeFieldDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достигните уровня {0} поля.
        /// </summary>
        internal static string UpgradeFieldElementBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldElementBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличивает базовую стоимость {0} с {1} до {2}.
        /// </summary>
        internal static string UpgradeFieldElementDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldElementDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Базовая ценность {0}.
        /// </summary>
        internal static string UpgradeFieldElementHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldElementHeaderTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игровое поле.
        /// </summary>
        internal static string UpgradeFieldHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldHeaderTextKey", resourceCulture);
            }
        }
    }
}
