//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchThree.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchThree.API.Resources.Localization.en-US", typeof(Localization_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max level reached.
        /// </summary>
        internal static string CommonMaxLevelReachedTextKey {
            get {
                return ResourceManager.GetString("CommonMaxLevelReachedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice ping!.
        /// </summary>
        internal static string CommonPingOk {
            get {
                return ResourceManager.GetString("CommonPingOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string CommonUndefinedTextKey {
            get {
                return ResourceManager.GetString("CommonUndefinedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to authorize. Please try again later. {0}.
        /// </summary>
        internal static string ExceptionAuthorizationTextKey {
            get {
                return ResourceManager.GetString("ExceptionAuthorizationTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve been banned for {0} hour(s).
        /// </summary>
        internal static string ExceptionBannedTextKey {
            get {
                return ResourceManager.GetString("ExceptionBannedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quest has already been completed today.
        /// </summary>
        internal static string ExceptionDailyLoginCompletedTodayTextKey {
            get {
                return ResourceManager.GetString("ExceptionDailyLoginCompletedTodayTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        internal static string ExceptionDefaultTextKey {
            get {
                return ResourceManager.GetString("ExceptionDefaultTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified item does not exist.
        /// </summary>
        internal static string ExceptionNoDataFoundTextKey {
            get {
                return ResourceManager.GetString("ExceptionNoDataFoundTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds on the balance.
        /// </summary>
        internal static string ExceptionNotEnoughBalanceTextKey {
            get {
                return ResourceManager.GetString("ExceptionNotEnoughBalanceTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough energy.
        /// </summary>
        internal static string ExceptionNotEnoughEnergyTextKey {
            get {
                return ResourceManager.GetString("ExceptionNotEnoughEnergyTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The quest is already completed.
        /// </summary>
        internal static string ExceptionQuestAlreadyCompletedTextKey {
            get {
                return ResourceManager.GetString("ExceptionQuestAlreadyCompletedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quest is no longer available.
        /// </summary>
        internal static string ExceptionQuestOutdatedTextKey {
            get {
                return ResourceManager.GetString("ExceptionQuestOutdatedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all conditions were met.
        /// </summary>
        internal static string ExceptionQuestsConditionNotMetTextKey {
            get {
                return ResourceManager.GetString("ExceptionQuestsConditionNotMetTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade conditions have not been met.
        /// </summary>
        internal static string ExceptionUpgradeConditionsTextKey {
            get {
                return ResourceManager.GetString("ExceptionUpgradeConditionsTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process the request. Please refresh the page and try again.
        /// </summary>
        internal static string ExceptionValidationTextKey {
            get {
                return ResourceManager.GetString("ExceptionValidationTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab league.
        /// </summary>
        internal static string LeagueCrabFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueCrabFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab.
        /// </summary>
        internal static string LeagueCrabTextKey {
            get {
                return ResourceManager.GetString("LeagueCrabTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin league.
        /// </summary>
        internal static string LeagueDolphinFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueDolphinFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin.
        /// </summary>
        internal static string LeagueDolphinTextKey {
            get {
                return ResourceManager.GetString("LeagueDolphinTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish league.
        /// </summary>
        internal static string LeagueFishFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueFishFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        internal static string LeagueFishTextKey {
            get {
                return ResourceManager.GetString("LeagueFishTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humpback whale league.
        /// </summary>
        internal static string LeagueHumpbackFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueHumpbackFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humpback whale.
        /// </summary>
        internal static string LeagueHumpbackTextKey {
            get {
                return ResourceManager.GetString("LeagueHumpbackTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octopus league.
        /// </summary>
        internal static string LeagueOctopusFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueOctopusFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octopus.
        /// </summary>
        internal static string LeagueOctopusTextKey {
            get {
                return ResourceManager.GetString("LeagueOctopusTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shark league.
        /// </summary>
        internal static string LeagueSharkFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueSharkFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shark.
        /// </summary>
        internal static string LeagueSharkTextKey {
            get {
                return ResourceManager.GetString("LeagueSharkTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrimp league.
        /// </summary>
        internal static string LeagueShrimpFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueShrimpFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrimp.
        /// </summary>
        internal static string LeagueShrimpTextKey {
            get {
                return ResourceManager.GetString("LeagueShrimpTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whale league.
        /// </summary>
        internal static string LeagueWhaleFullNameTextKey {
            get {
                return ResourceManager.GetString("LeagueWhaleFullNameTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whale.
        /// </summary>
        internal static string LeagueWhaleTextKey {
            get {
                return ResourceManager.GetString("LeagueWhaleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://t.me/PingWinGame.
        /// </summary>
        internal static string LinkNewsChannelTextKey {
            get {
                return ResourceManager.GetString("LinkNewsChannelTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get an extra reward for the first friend you invite.
        /// </summary>
        internal static string QuestInvite1FriendDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestInvite1FriendDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite 1 friend.
        /// </summary>
        internal static string QuestInvite1FriendTittleTextKey {
            get {
                return ResourceManager.GetString("QuestInvite1FriendTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get extra rewards for the first two friends you invite.
        /// </summary>
        internal static string QuestInvite3FriendDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestInvite3FriendDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite 3 friend.
        /// </summary>
        internal static string QuestInvite3FriendTittleTextKey {
            get {
                return ResourceManager.GetString("QuestInvite3FriendTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get extra rewards for the first five friends you invite.
        /// </summary>
        internal static string QuestInvite5FriendDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestInvite5FriendDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite 5 friend.
        /// </summary>
        internal static string QuestInvite5FriendTittleTextKey {
            get {
                return ResourceManager.GetString("QuestInvite5FriendTittleTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be one of the first to know the news.
        /// </summary>
        internal static string QuestSubscribeToNewsChannelDescriptionTextKey {
            get {
                return ResourceManager.GetString("QuestSubscribeToNewsChannelDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join our TG channel.
        /// </summary>
        internal static string QuestSubscribeToNewsChannelHeaderTextKey {
            get {
                return ResourceManager.GetString("QuestSubscribeToNewsChannelHeaderTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string UpgradeCategoryEnergyTextKey {
            get {
                return ResourceManager.GetString("UpgradeCategoryEnergyTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto.
        /// </summary>
        internal static string UpgradeCategoryFieldElementsTextKey {
            get {
                return ResourceManager.GetString("UpgradeCategoryFieldElementsTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playing field.
        /// </summary>
        internal static string UpgradeCategoryFieldTextKey {
            get {
                return ResourceManager.GetString("UpgradeCategoryFieldTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s limit is reached.
        /// </summary>
        internal static string UpgradeEnergyDrinkBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyDrinkBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restores {0} energy.
        /// </summary>
        internal static string UpgradeEnergyDrinkDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyDrinkDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy drink.
        /// </summary>
        internal static string UpgradeEnergyDrinkHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyDrinkHeaderTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach level {0} of energy reserve.
        /// </summary>
        internal static string UpgradeEnergyRecoveryBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyRecoveryBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases energy recovery speed from {0} sec to {1} sec.
        /// </summary>
        internal static string UpgradeEnergyRecoveryDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyRecoveryDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recovery speed.
        /// </summary>
        internal static string UpgradeEnergyRecoveryHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyRecoveryHeaderTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite {0} more friend(s).
        /// </summary>
        internal static string UpgradeEnergyReserveBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyReserveBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boosts energy reserves by 5.
        /// </summary>
        internal static string UpgradeEnergyReserveDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyReserveDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy reserve.
        /// </summary>
        internal static string UpgradeEnergyReserveHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyReserveHeaderTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases the field size by 1 cell.
        /// </summary>
        internal static string UpgradeFieldDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reach level {0} of the field.
        /// </summary>
        internal static string UpgradeFieldElementBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldElementBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increases base value of {0} from {1} to {2}.
        /// </summary>
        internal static string UpgradeFieldElementDescriptionTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldElementDescriptionTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base value of {0}.
        /// </summary>
        internal static string UpgradeFieldElementHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldElementHeaderTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade the field.
        /// </summary>
        internal static string UpgradeFieldHeaderTextKey {
            get {
                return ResourceManager.GetString("UpgradeFieldHeaderTextKey", resourceCulture);
            }
        }
    }
}
