//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchThree.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchThree.API.Resources.Localization.ru-RU", typeof(Localization_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краб.
        /// </summary>
        internal static string CrabLeagueKey {
            get {
                return ResourceManager.GetString("CrabLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла непредвиденная ошибка.
        /// </summary>
        internal static string DefaultExceptionKey {
            get {
                return ResourceManager.GetString("DefaultExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дельфин.
        /// </summary>
        internal static string DolphinLeagueKey {
            get {
                return ResourceManager.GetString("DolphinLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергия.
        /// </summary>
        internal static string EnergyCategoryTextKey {
            get {
                return ResourceManager.GetString("EnergyCategoryTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сегодняшний лимит исчерпан.
        /// </summary>
        internal static string EnergyDrinkBlockingTextKey {
            get {
                return ResourceManager.GetString("EnergyDrinkBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстанавливает {0} энергии.
        /// </summary>
        internal static string EnergyDrinkDescriptionKey {
            get {
                return ResourceManager.GetString("EnergyDrinkDescriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Энергетик.
        /// </summary>
        internal static string EnergyDrinkHeaderKey {
            get {
                return ResourceManager.GetString("EnergyDrinkHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Игровое поле.
        /// </summary>
        internal static string FieldCategoryTextKey {
            get {
                return ResourceManager.GetString("FieldCategoryTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рыба.
        /// </summary>
        internal static string FishLeagueKey {
            get {
                return ResourceManager.GetString("FishLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Горбатый кит.
        /// </summary>
        internal static string HumpbackLeagueKey {
            get {
                return ResourceManager.GetString("HumpbackLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достигнут максимальный уровень.
        /// </summary>
        internal static string MaxLevelReachedTextKey {
            get {
                return ResourceManager.GetString("MaxLevelReachedTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Указанный элемент не существует.
        /// </summary>
        internal static string NoDataFoundExceptionKey {
            get {
                return ResourceManager.GetString("NoDataFoundExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно средств на балансе.
        /// </summary>
        internal static string NotEnoughBalanceExceptionKey {
            get {
                return ResourceManager.GetString("NotEnoughBalanceExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Осьминог.
        /// </summary>
        internal static string OctopusLeagueKey {
            get {
                return ResourceManager.GetString("OctopusLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ну пинганул.
        /// </summary>
        internal static string PingOk {
            get {
                return ResourceManager.GetString("PingOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Акула.
        /// </summary>
        internal static string SharkLeagueKey {
            get {
                return ResourceManager.GetString("SharkLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Креветка.
        /// </summary>
        internal static string ShrimpLeagueKey {
            get {
                return ResourceManager.GetString("ShrimpLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не определено.
        /// </summary>
        internal static string UndefinedKey {
            get {
                return ResourceManager.GetString("UndefinedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Условия улучшения не были выполнены.
        /// </summary>
        internal static string UpgradeConditionsExceptionKey {
            get {
                return ResourceManager.GetString("UpgradeConditionsExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Достигните {0} уровня запаса энергии.
        /// </summary>
        internal static string UpgradeEnergyRecoveryBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyRecoveryBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повышает скорость восстановления энергии.
        /// </summary>
        internal static string UpgradeEnergyRecoveryDescriptionKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyRecoveryDescriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скорость восстановления.
        /// </summary>
        internal static string UpgradeEnergyRecoveryHeaderKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyRecoveryHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пригласите еще {0} друга.
        /// </summary>
        internal static string UpgradeEnergyReserveBlockingTextKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyReserveBlockingTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличивает запас энергии на 5.
        /// </summary>
        internal static string UpgradeEnergyReserveDescriptionKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyReserveDescriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запас энергии.
        /// </summary>
        internal static string UpgradeEnergyReserveHeaderKey {
            get {
                return ResourceManager.GetString("UpgradeEnergyReserveHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Увеличивает размер поля на 1 клетку.
        /// </summary>
        internal static string UpgradeFieldDescriptionKey {
            get {
                return ResourceManager.GetString("UpgradeFieldDescriptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Улучшить поле.
        /// </summary>
        internal static string UpgradeFieldHeaderKey {
            get {
                return ResourceManager.GetString("UpgradeFieldHeaderKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кит.
        /// </summary>
        internal static string WhaleLeagueKey {
            get {
                return ResourceManager.GetString("WhaleLeagueKey", resourceCulture);
            }
        }
    }
}
