//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MatchThree.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MatchThree.API.Resources.Localization.en-US", typeof(Localization_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crab.
        /// </summary>
        internal static string CrabLeagueKey {
            get {
                return ResourceManager.GetString("CrabLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred.
        /// </summary>
        internal static string DefaultExceptionKey {
            get {
                return ResourceManager.GetString("DefaultExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dolphin.
        /// </summary>
        internal static string DolphinLeagueKey {
            get {
                return ResourceManager.GetString("DolphinLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Energy.
        /// </summary>
        internal static string EnergyCategoryTextKey {
            get {
                return ResourceManager.GetString("EnergyCategoryTextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish.
        /// </summary>
        internal static string FishLeagueKey {
            get {
                return ResourceManager.GetString("FishLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humpback.
        /// </summary>
        internal static string HumpbackLeagueKey {
            get {
                return ResourceManager.GetString("HumpbackLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max level reached.
        /// </summary>
        internal static string MaxLevelReachedExceptionKey {
            get {
                return ResourceManager.GetString("MaxLevelReachedExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified item does not exist.
        /// </summary>
        internal static string NoDataFoundExceptionKey {
            get {
                return ResourceManager.GetString("NoDataFoundExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient funds on the balance.
        /// </summary>
        internal static string NotEnoughBalanceExceptionKey {
            get {
                return ResourceManager.GetString("NotEnoughBalanceExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octopus.
        /// </summary>
        internal static string OctopusLeagueKey {
            get {
                return ResourceManager.GetString("OctopusLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nice ping!.
        /// </summary>
        internal static string PingOk {
            get {
                return ResourceManager.GetString("PingOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shark.
        /// </summary>
        internal static string SharkLeagueKey {
            get {
                return ResourceManager.GetString("SharkLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrimp.
        /// </summary>
        internal static string ShrimpLeagueKey {
            get {
                return ResourceManager.GetString("ShrimpLeagueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string UndefinedKey {
            get {
                return ResourceManager.GetString("UndefinedKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade conditions have not been met.
        /// </summary>
        internal static string UpgradeConditionsExceptionKey {
            get {
                return ResourceManager.GetString("UpgradeConditionsExceptionKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whale.
        /// </summary>
        internal static string WhaleLeagueKey {
            get {
                return ResourceManager.GetString("WhaleLeagueKey", resourceCulture);
            }
        }
    }
}
