// <auto-generated />
using System;
using MatchThree.Repository.MSSQL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatchThree.Repository.MSSQL.Migrations
{
    [DbContext(typeof(MatchThreeDbContext))]
    [Migration("20241103141733_AddCopletedQuestsTabel")]
    partial class AddCopletedQuestsTabel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.BalanceDbModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint");

                    b.Property<decimal>("OverallBalance")
                        .HasColumnType("decimal(20,0)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("Balances");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.CompletedQuestsDbModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("QuestIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("CompletedQuests");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.EnergyDbModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("AvailableEnergyDrinkAmount")
                        .HasColumnType("int");

                    b.Property<int>("CurrentReserve")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastRecoveryStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxReserve")
                        .HasColumnType("int");

                    b.Property<int>("PurchasableEnergyDrinkAmount")
                        .HasColumnType("int");

                    b.Property<int>("RecoveryLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("Energies");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.FieldDbModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FieldLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.FieldElementDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Element")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Element")
                        .IsUnique();

                    b.ToTable("FieldElements");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.LeaderboardMemberDbModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("League")
                        .HasColumnType("int");

                    b.Property<decimal>("OverallBalance")
                        .HasColumnType("decimal(20,0)");

                    b.Property<int>("TopSpot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("League");

                    b.ToTable("LeaderboardMembers");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.ReferralDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ReferralUserId")
                        .HasColumnType("bigint");

                    b.Property<long>("ReferrerUserId")
                        .HasColumnType("bigint");

                    b.Property<bool>("WasPremium")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ReferralUserId")
                        .IsUnique();

                    b.HasIndex("ReferrerUserId", "ReferralUserId")
                        .IsUnique();

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.UserDbModel", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("SessionHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.BalanceDbModel", b =>
                {
                    b.HasOne("MatchThree.Repository.MSSQL.Models.UserDbModel", "User")
                        .WithOne("Balance")
                        .HasForeignKey("MatchThree.Repository.MSSQL.Models.BalanceDbModel", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.EnergyDbModel", b =>
                {
                    b.HasOne("MatchThree.Repository.MSSQL.Models.UserDbModel", "User")
                        .WithOne("Energy")
                        .HasForeignKey("MatchThree.Repository.MSSQL.Models.EnergyDbModel", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.FieldDbModel", b =>
                {
                    b.HasOne("MatchThree.Repository.MSSQL.Models.UserDbModel", "User")
                        .WithOne("FieldElementLevel")
                        .HasForeignKey("MatchThree.Repository.MSSQL.Models.FieldDbModel", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.FieldElementDbModel", b =>
                {
                    b.HasOne("MatchThree.Repository.MSSQL.Models.UserDbModel", "User")
                        .WithMany("FieldElements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.ReferralDbModel", b =>
                {
                    b.HasOne("MatchThree.Repository.MSSQL.Models.UserDbModel", "Referral")
                        .WithOne("Referrer")
                        .HasForeignKey("MatchThree.Repository.MSSQL.Models.ReferralDbModel", "ReferralUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MatchThree.Repository.MSSQL.Models.UserDbModel", "Referrer")
                        .WithMany("Referrals")
                        .HasForeignKey("ReferrerUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Referral");

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("MatchThree.Repository.MSSQL.Models.UserDbModel", b =>
                {
                    b.Navigation("Balance");

                    b.Navigation("Energy");

                    b.Navigation("FieldElementLevel");

                    b.Navigation("FieldElements");

                    b.Navigation("Referrals");

                    b.Navigation("Referrer");
                });
#pragma warning restore 612, 618
        }
    }
}
